export const SET_USER = 'SET_USER'
export const CLEAR_USER = 'CLEAR_USER'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const SET_CURRENT_CHANNEL = 'SET_CURRENT_CHANNEL'
export const SET_CHANNELS = 'SET_CHANNELS'
export const ADD_CHANNEL_SUCCESS = 'ADD_CHANNEL_SUCCESS'

export const ADD_MESSAGE_SUCCES = 'ADD_MESSAGE_SUCCES'
export const SET_MESSAGES = 'SET_MESSAGES'


