export const SET_USER = 'SET_USER'
export const CLEAR_USER = 'CLEAR_USER'

export const SET_CURRENT_CHANNEL = 'SET_CURRENT_CHANNEL'
export const SET_CHANNELS = 'SET_CHANNELS'
export const ADD_CHANNEL_SUCCESS = 'ADD_CHANNEL_SUCCESS'


